/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApiStatus = IDL.Record({
  'lastBdlCallStatus' : IDL.Opt(IDL.Text),
  'oddsApiConfigured' : IDL.Bool,
  'openAiConfigured' : IDL.Bool,
  'bdlApiConfigured' : IDL.Bool,
  'lastOddsApiCallStatus' : IDL.Opt(IDL.Text),
});
export const BetStatus = IDL.Variant({
  'won' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'lost' : IDL.Null,
  'push' : IDL.Null,
});
export const BetType = IDL.Variant({
  'gameTotal' : IDL.Null,
  'playerProp' : IDL.Null,
  'spread' : IDL.Null,
});
export const GameId = IDL.Text;
export const BetRecommendation = IDL.Record({
  'id' : IDL.Text,
  'status' : BetStatus,
  'result' : IDL.Opt(IDL.Text),
  'homeTeam' : IDL.Text,
  'gameResult' : IDL.Opt(IDL.Text),
  'betType' : BetType,
  'gameId' : GameId,
  'description' : IDL.Text,
  'reasoning' : IDL.Text,
  'updatedAt' : IDL.Opt(IDL.Int),
  'recommendedAt' : IDL.Int,
  'awayTeam' : IDL.Text,
  'gameDate' : IDL.Text,
  'preGameOdds' : IDL.Opt(IDL.Text),
  'confidence' : IDL.Nat,
});
export const BetHistoryStats = IDL.Record({
  'lostBets' : IDL.Nat,
  'wonBets' : IDL.Nat,
  'totalBets' : IDL.Nat,
  'pendingBets' : IDL.Nat,
  'winRate' : IDL.Float64,
});
export const GameStatus = IDL.Variant({
  'final' : IDL.Null,
  'scheduled' : IDL.Null,
  'inProgress' : IDL.Null,
  'postponed' : IDL.Null,
});
export const TeamId = IDL.Text;
export const Team = IDL.Record({
  'id' : TeamId,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'abbreviation' : IDL.Text,
  'record' : IDL.Text,
});
export const OddsLine = IDL.Record({
  'homeMoneyline' : IDL.Opt(IDL.Int),
  'overUnder' : IDL.Opt(IDL.Float64),
  'awaySpreadOdds' : IDL.Opt(IDL.Int),
  'awayMoneyline' : IDL.Opt(IDL.Int),
  'overOdds' : IDL.Opt(IDL.Int),
  'awaySpread' : IDL.Opt(IDL.Float64),
  'homeSpreadOdds' : IDL.Opt(IDL.Int),
  'homeSpread' : IDL.Opt(IDL.Float64),
  'bookmaker' : IDL.Text,
  'underOdds' : IDL.Opt(IDL.Int),
  'updatedAt' : IDL.Text,
});
export const Game = IDL.Record({
  'id' : GameId,
  'status' : GameStatus,
  'venue' : IDL.Text,
  'displayTime' : IDL.Text,
  'homeTeam' : Team,
  'odds' : IDL.Vec(OddsLine),
  'series' : IDL.Opt(IDL.Text),
  'awayTeam' : Team,
  'gameTime' : IDL.Text,
});
export const PlayerId = IDL.Text;
export const InjuryReport = IDL.Record({
  'status' : IDL.Text,
  'playerId' : PlayerId,
  'team' : IDL.Text,
  'description' : IDL.Text,
  'updatedAt' : IDL.Text,
  'playerName' : IDL.Text,
});
export const Discrepancy = IDL.Record({
  'gap' : IDL.Float64,
  'minValue' : IDL.Float64,
  'minBook' : IDL.Text,
  'betType' : IDL.Text,
  'maxBook' : IDL.Text,
  'maxValue' : IDL.Float64,
});
export const TeamStats = IDL.Record({
  'pace' : IDL.Opt(IDL.Float64),
  'recentForm' : IDL.Vec(IDL.Nat),
  'homeAwayRecord' : IDL.Text,
  'defensiveRating' : IDL.Opt(IDL.Float64),
  'teamId' : TeamId,
  'restDays' : IDL.Nat,
  'offensiveRating' : IDL.Opt(IDL.Float64),
  'pointsPerGame' : IDL.Opt(IDL.Float64),
});
export const GameInvestigation = IDL.Record({
  'game' : Game,
  'odds' : IDL.Vec(OddsLine),
  'injuries' : IDL.Vec(InjuryReport),
  'discrepancies' : IDL.Vec(Discrepancy),
  'homeTeamStats' : TeamStats,
  'awayTeamStats' : TeamStats,
});
export const ApiError = IDL.Variant({
  'networkError' : IDL.Text,
  'notFound' : IDL.Text,
  'parseError' : IDL.Text,
  'rateLimited' : IDL.Text,
  'unavailable' : IDL.Text,
});
export const Result_6 = IDL.Variant({
  'ok' : GameInvestigation,
  'err' : ApiError,
});
export const PaceProfile = IDL.Record({
  'defensiveEfficiency' : IDL.Float64,
  'pace' : IDL.Float64,
  'avgPointsAgainst' : IDL.Float64,
  'avgPointsFor' : IDL.Float64,
  'offensiveEfficiency' : IDL.Float64,
  'teamId' : TeamId,
  'last5Avg' : IDL.Float64,
});
export const RefereeProfile = IDL.Record({
  'overRate' : IDL.Opt(IDL.Float64),
  'name' : IDL.Text,
  'avgFoulsPerGame' : IDL.Opt(IDL.Float64),
  'avgFreeThrowsPerGame' : IDL.Opt(IDL.Float64),
});
export const ScoringTrend = IDL.Record({
  'result' : IDL.Text,
  'overUnder' : IDL.Float64,
  'teamTotal' : IDL.Float64,
  'date' : IDL.Text,
  'gameTotal' : IDL.Float64,
  'opponent' : IDL.Text,
});
export const TotalsConfidenceReport = IDL.Record({
  'overUnderEdge' : IDL.Text,
  'keyFactors' : IDL.Vec(IDL.Text),
  'reasoning' : IDL.Text,
  'score' : IDL.Nat,
  'projectedTotal' : IDL.Opt(IDL.Float64),
  'grade' : IDL.Text,
  'recommendation' : IDL.Text,
});
export const GameTotal = IDL.Record({
  'homePace' : PaceProfile,
  'gameId' : GameId,
  'refereeProfile' : IDL.Opt(RefereeProfile),
  'impliedTotal' : IDL.Opt(IDL.Float64),
  'projectedTotal' : IDL.Opt(IDL.Float64),
  'recentTrends' : IDL.Vec(ScoringTrend),
  'confidenceReport' : IDL.Opt(TotalsConfidenceReport),
  'awayPace' : PaceProfile,
  'injuryImpact' : IDL.Text,
});
export const Result_5 = IDL.Variant({ 'ok' : GameTotal, 'err' : ApiError });
export const Result_4 = IDL.Variant({
  'ok' : IDL.Vec(OddsLine),
  'err' : ApiError,
});
export const Player = IDL.Record({
  'id' : PlayerId,
  'name' : IDL.Text,
  'team' : IDL.Text,
  'jerseyNumber' : IDL.Text,
  'injuryStatus' : IDL.Text,
  'position' : IDL.Text,
});
export const PropLine = IDL.Record({
  'overOdds' : IDL.Int,
  'line' : IDL.Float64,
  'bookmaker' : IDL.Text,
  'underOdds' : IDL.Int,
});
export const ConfidenceReport = IDL.Record({
  'keyFactors' : IDL.Vec(IDL.Text),
  'projectedPoints' : IDL.Opt(IDL.Float64),
  'reasoning' : IDL.Text,
  'score' : IDL.Nat,
  'grade' : IDL.Text,
  'recommendation' : IDL.Text,
});
export const PlayerRecentGame = IDL.Record({
  'fieldGoalAttempts' : IDL.Float64,
  'date' : IDL.Text,
  'minutes' : IDL.Float64,
  'usageRate' : IDL.Float64,
  'points' : IDL.Float64,
  'opponent' : IDL.Text,
});
export const PlayerProp = IDL.Record({
  'seasonAvgPoints' : IDL.Float64,
  'player' : Player,
  'seasonUsageRate' : IDL.Float64,
  'matchupDefRating' : IDL.Opt(IDL.Float64),
  'seasonAvgMinutes' : IDL.Float64,
  'propLines' : IDL.Vec(PropLine),
  'confidenceReport' : IDL.Opt(ConfidenceReport),
  'backToBack' : IDL.Bool,
  'recentGames' : IDL.Vec(PlayerRecentGame),
  'homeAwaySplit' : IDL.Float64,
});
export const PlayerPropsAnalysis = IDL.Record({
  'gameId' : GameId,
  'players' : IDL.Vec(PlayerProp),
  'analysisGeneratedAt' : IDL.Text,
});
export const Result_3 = IDL.Variant({
  'ok' : PlayerPropsAnalysis,
  'err' : ApiError,
});
export const GamesResponse = IDL.Record({
  'gamesDate' : IDL.Text,
  'isUpcomingDate' : IDL.Bool,
  'games' : IDL.Vec(Game),
});
export const Result_2 = IDL.Variant({ 'ok' : GamesResponse, 'err' : ApiError });
export const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : ApiError });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : ApiError });

export const idlService = IDL.Service({
  'getApiStatus' : IDL.Func([], [ApiStatus], ['query']),
  'getBetHistory' : IDL.Func([], [IDL.Vec(BetRecommendation)], ['query']),
  'getBetHistoryStats' : IDL.Func([], [BetHistoryStats], ['query']),
  'getGameInvestigation' : IDL.Func([GameId, IDL.Text], [Result_6], []),
  'getGameTotalsAnalysis' : IDL.Func(
      [GameId, IDL.Text, IDL.Text],
      [Result_5],
      [],
    ),
  'getHistoryContext' : IDL.Func([], [IDL.Text], ['query']),
  'getMultiBookOdds' : IDL.Func([GameId], [Result_4], []),
  'getPlayerPropsAnalysis' : IDL.Func([GameId], [Result_3], []),
  'getPropsAIAnalysis' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getTodaysGames' : IDL.Func([], [Result_2], []),
  'getTotalsAIAnalysis' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'isBdlApiConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isOddsApiConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveBetRecommendation' : IDL.Func([BetRecommendation], [Result_1], []),
  'setBdlApiKey' : IDL.Func([IDL.Text], [], []),
  'setOddsApiKey' : IDL.Func([IDL.Text], [], []),
  'setOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBetOutcome' : IDL.Func(
      [IDL.Text, BetStatus, IDL.Opt(IDL.Text)],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApiStatus = IDL.Record({
    'lastBdlCallStatus' : IDL.Opt(IDL.Text),
    'oddsApiConfigured' : IDL.Bool,
    'openAiConfigured' : IDL.Bool,
    'bdlApiConfigured' : IDL.Bool,
    'lastOddsApiCallStatus' : IDL.Opt(IDL.Text),
  });
  const BetStatus = IDL.Variant({
    'won' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'lost' : IDL.Null,
    'push' : IDL.Null,
  });
  const BetType = IDL.Variant({
    'gameTotal' : IDL.Null,
    'playerProp' : IDL.Null,
    'spread' : IDL.Null,
  });
  const GameId = IDL.Text;
  const BetRecommendation = IDL.Record({
    'id' : IDL.Text,
    'status' : BetStatus,
    'result' : IDL.Opt(IDL.Text),
    'homeTeam' : IDL.Text,
    'gameResult' : IDL.Opt(IDL.Text),
    'betType' : BetType,
    'gameId' : GameId,
    'description' : IDL.Text,
    'reasoning' : IDL.Text,
    'updatedAt' : IDL.Opt(IDL.Int),
    'recommendedAt' : IDL.Int,
    'awayTeam' : IDL.Text,
    'gameDate' : IDL.Text,
    'preGameOdds' : IDL.Opt(IDL.Text),
    'confidence' : IDL.Nat,
  });
  const BetHistoryStats = IDL.Record({
    'lostBets' : IDL.Nat,
    'wonBets' : IDL.Nat,
    'totalBets' : IDL.Nat,
    'pendingBets' : IDL.Nat,
    'winRate' : IDL.Float64,
  });
  const GameStatus = IDL.Variant({
    'final' : IDL.Null,
    'scheduled' : IDL.Null,
    'inProgress' : IDL.Null,
    'postponed' : IDL.Null,
  });
  const TeamId = IDL.Text;
  const Team = IDL.Record({
    'id' : TeamId,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'abbreviation' : IDL.Text,
    'record' : IDL.Text,
  });
  const OddsLine = IDL.Record({
    'homeMoneyline' : IDL.Opt(IDL.Int),
    'overUnder' : IDL.Opt(IDL.Float64),
    'awaySpreadOdds' : IDL.Opt(IDL.Int),
    'awayMoneyline' : IDL.Opt(IDL.Int),
    'overOdds' : IDL.Opt(IDL.Int),
    'awaySpread' : IDL.Opt(IDL.Float64),
    'homeSpreadOdds' : IDL.Opt(IDL.Int),
    'homeSpread' : IDL.Opt(IDL.Float64),
    'bookmaker' : IDL.Text,
    'underOdds' : IDL.Opt(IDL.Int),
    'updatedAt' : IDL.Text,
  });
  const Game = IDL.Record({
    'id' : GameId,
    'status' : GameStatus,
    'venue' : IDL.Text,
    'displayTime' : IDL.Text,
    'homeTeam' : Team,
    'odds' : IDL.Vec(OddsLine),
    'series' : IDL.Opt(IDL.Text),
    'awayTeam' : Team,
    'gameTime' : IDL.Text,
  });
  const PlayerId = IDL.Text;
  const InjuryReport = IDL.Record({
    'status' : IDL.Text,
    'playerId' : PlayerId,
    'team' : IDL.Text,
    'description' : IDL.Text,
    'updatedAt' : IDL.Text,
    'playerName' : IDL.Text,
  });
  const Discrepancy = IDL.Record({
    'gap' : IDL.Float64,
    'minValue' : IDL.Float64,
    'minBook' : IDL.Text,
    'betType' : IDL.Text,
    'maxBook' : IDL.Text,
    'maxValue' : IDL.Float64,
  });
  const TeamStats = IDL.Record({
    'pace' : IDL.Opt(IDL.Float64),
    'recentForm' : IDL.Vec(IDL.Nat),
    'homeAwayRecord' : IDL.Text,
    'defensiveRating' : IDL.Opt(IDL.Float64),
    'teamId' : TeamId,
    'restDays' : IDL.Nat,
    'offensiveRating' : IDL.Opt(IDL.Float64),
    'pointsPerGame' : IDL.Opt(IDL.Float64),
  });
  const GameInvestigation = IDL.Record({
    'game' : Game,
    'odds' : IDL.Vec(OddsLine),
    'injuries' : IDL.Vec(InjuryReport),
    'discrepancies' : IDL.Vec(Discrepancy),
    'homeTeamStats' : TeamStats,
    'awayTeamStats' : TeamStats,
  });
  const ApiError = IDL.Variant({
    'networkError' : IDL.Text,
    'notFound' : IDL.Text,
    'parseError' : IDL.Text,
    'rateLimited' : IDL.Text,
    'unavailable' : IDL.Text,
  });
  const Result_6 = IDL.Variant({ 'ok' : GameInvestigation, 'err' : ApiError });
  const PaceProfile = IDL.Record({
    'defensiveEfficiency' : IDL.Float64,
    'pace' : IDL.Float64,
    'avgPointsAgainst' : IDL.Float64,
    'avgPointsFor' : IDL.Float64,
    'offensiveEfficiency' : IDL.Float64,
    'teamId' : TeamId,
    'last5Avg' : IDL.Float64,
  });
  const RefereeProfile = IDL.Record({
    'overRate' : IDL.Opt(IDL.Float64),
    'name' : IDL.Text,
    'avgFoulsPerGame' : IDL.Opt(IDL.Float64),
    'avgFreeThrowsPerGame' : IDL.Opt(IDL.Float64),
  });
  const ScoringTrend = IDL.Record({
    'result' : IDL.Text,
    'overUnder' : IDL.Float64,
    'teamTotal' : IDL.Float64,
    'date' : IDL.Text,
    'gameTotal' : IDL.Float64,
    'opponent' : IDL.Text,
  });
  const TotalsConfidenceReport = IDL.Record({
    'overUnderEdge' : IDL.Text,
    'keyFactors' : IDL.Vec(IDL.Text),
    'reasoning' : IDL.Text,
    'score' : IDL.Nat,
    'projectedTotal' : IDL.Opt(IDL.Float64),
    'grade' : IDL.Text,
    'recommendation' : IDL.Text,
  });
  const GameTotal = IDL.Record({
    'homePace' : PaceProfile,
    'gameId' : GameId,
    'refereeProfile' : IDL.Opt(RefereeProfile),
    'impliedTotal' : IDL.Opt(IDL.Float64),
    'projectedTotal' : IDL.Opt(IDL.Float64),
    'recentTrends' : IDL.Vec(ScoringTrend),
    'confidenceReport' : IDL.Opt(TotalsConfidenceReport),
    'awayPace' : PaceProfile,
    'injuryImpact' : IDL.Text,
  });
  const Result_5 = IDL.Variant({ 'ok' : GameTotal, 'err' : ApiError });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Vec(OddsLine), 'err' : ApiError });
  const Player = IDL.Record({
    'id' : PlayerId,
    'name' : IDL.Text,
    'team' : IDL.Text,
    'jerseyNumber' : IDL.Text,
    'injuryStatus' : IDL.Text,
    'position' : IDL.Text,
  });
  const PropLine = IDL.Record({
    'overOdds' : IDL.Int,
    'line' : IDL.Float64,
    'bookmaker' : IDL.Text,
    'underOdds' : IDL.Int,
  });
  const ConfidenceReport = IDL.Record({
    'keyFactors' : IDL.Vec(IDL.Text),
    'projectedPoints' : IDL.Opt(IDL.Float64),
    'reasoning' : IDL.Text,
    'score' : IDL.Nat,
    'grade' : IDL.Text,
    'recommendation' : IDL.Text,
  });
  const PlayerRecentGame = IDL.Record({
    'fieldGoalAttempts' : IDL.Float64,
    'date' : IDL.Text,
    'minutes' : IDL.Float64,
    'usageRate' : IDL.Float64,
    'points' : IDL.Float64,
    'opponent' : IDL.Text,
  });
  const PlayerProp = IDL.Record({
    'seasonAvgPoints' : IDL.Float64,
    'player' : Player,
    'seasonUsageRate' : IDL.Float64,
    'matchupDefRating' : IDL.Opt(IDL.Float64),
    'seasonAvgMinutes' : IDL.Float64,
    'propLines' : IDL.Vec(PropLine),
    'confidenceReport' : IDL.Opt(ConfidenceReport),
    'backToBack' : IDL.Bool,
    'recentGames' : IDL.Vec(PlayerRecentGame),
    'homeAwaySplit' : IDL.Float64,
  });
  const PlayerPropsAnalysis = IDL.Record({
    'gameId' : GameId,
    'players' : IDL.Vec(PlayerProp),
    'analysisGeneratedAt' : IDL.Text,
  });
  const Result_3 = IDL.Variant({
    'ok' : PlayerPropsAnalysis,
    'err' : ApiError,
  });
  const GamesResponse = IDL.Record({
    'gamesDate' : IDL.Text,
    'isUpcomingDate' : IDL.Bool,
    'games' : IDL.Vec(Game),
  });
  const Result_2 = IDL.Variant({ 'ok' : GamesResponse, 'err' : ApiError });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : ApiError });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : ApiError });
  
  return IDL.Service({
    'getApiStatus' : IDL.Func([], [ApiStatus], ['query']),
    'getBetHistory' : IDL.Func([], [IDL.Vec(BetRecommendation)], ['query']),
    'getBetHistoryStats' : IDL.Func([], [BetHistoryStats], ['query']),
    'getGameInvestigation' : IDL.Func([GameId, IDL.Text], [Result_6], []),
    'getGameTotalsAnalysis' : IDL.Func(
        [GameId, IDL.Text, IDL.Text],
        [Result_5],
        [],
      ),
    'getHistoryContext' : IDL.Func([], [IDL.Text], ['query']),
    'getMultiBookOdds' : IDL.Func([GameId], [Result_4], []),
    'getPlayerPropsAnalysis' : IDL.Func([GameId], [Result_3], []),
    'getPropsAIAnalysis' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getTodaysGames' : IDL.Func([], [Result_2], []),
    'getTotalsAIAnalysis' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'isBdlApiConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isOddsApiConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveBetRecommendation' : IDL.Func([BetRecommendation], [Result_1], []),
    'setBdlApiKey' : IDL.Func([IDL.Text], [], []),
    'setOddsApiKey' : IDL.Func([IDL.Text], [], []),
    'setOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBetOutcome' : IDL.Func(
        [IDL.Text, BetStatus, IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };