/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApiError = { 'networkError' : string } |
  { 'notFound' : string } |
  { 'parseError' : string } |
  { 'rateLimited' : string } |
  { 'unavailable' : string };
export interface ApiStatus {
  'lastBdlCallStatus' : [] | [string],
  'oddsApiConfigured' : boolean,
  'openAiConfigured' : boolean,
  'bdlApiConfigured' : boolean,
  'lastOddsApiCallStatus' : [] | [string],
}
export interface BetHistoryStats {
  'lostBets' : bigint,
  'wonBets' : bigint,
  'totalBets' : bigint,
  'pendingBets' : bigint,
  'winRate' : number,
}
export interface BetRecommendation {
  'id' : string,
  'status' : BetStatus,
  'result' : [] | [string],
  'homeTeam' : string,
  'gameResult' : [] | [string],
  'betType' : BetType,
  'gameId' : GameId,
  'description' : string,
  'reasoning' : string,
  'updatedAt' : [] | [bigint],
  'recommendedAt' : bigint,
  'awayTeam' : string,
  'gameDate' : string,
  'preGameOdds' : [] | [string],
  'confidence' : bigint,
  'closingLine' : [] | [string],
  'clvScore' : [] | [number],
}
export type BetStatus = { 'won' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'lost' : null } |
  { 'push' : null };
export type BetType = { 'gameTotal' : null } |
  { 'playerProp' : null } |
  { 'spread' : null };
export interface ConfidenceReport {
  'keyFactors' : Array<string>,
  'projectedPoints' : [] | [number],
  'reasoning' : string,
  'score' : bigint,
  'grade' : string,
  'recommendation' : string,
}
export interface Discrepancy {
  'gap' : number,
  'minValue' : number,
  'minBook' : string,
  'betType' : string,
  'maxBook' : string,
  'maxValue' : number,
}
export interface Game {
  'id' : GameId,
  'status' : GameStatus,
  'venue' : string,
  'displayTime' : string,
  'homeTeam' : Team,
  'odds' : Array<OddsLine>,
  'series' : [] | [string],
  'awayTeam' : Team,
  'gameTime' : string,
}
export type GameId = string;
export interface LineMovement {
  'openingSpread' : [] | [number],
  'currentSpread' : [] | [number],
  'spreadMove' : number,
  'openingTotal' : [] | [number],
  'currentTotal' : [] | [number],
  'totalMove' : number,
  'steamAlert' : boolean,
  'sharpSide' : string,
}
export interface RestAdvantage {
  'homeRestDays' : bigint,
  'awayRestDays' : bigint,
  'advantage' : string,
  'impactDescription' : string,
}
export interface SituationalAngle {
  'name' : string,
  'description' : string,
  'edge' : string,
  'confidence' : bigint,
}
export interface GameInvestigation {
  'game' : Game,
  'odds' : Array<OddsLine>,
  'injuries' : Array<InjuryReport>,
  'discrepancies' : Array<Discrepancy>,
  'homeTeamStats' : TeamStats,
  'awayTeamStats' : TeamStats,
  'lineMovement' : [] | [LineMovement],
  'restAdvantage' : [] | [RestAdvantage],
  'situationalAngles' : Array<SituationalAngle>,
  'refereeProfile' : [] | [RefereeProfile],
}
export type GameStatus = { 'final' : null } |
  { 'scheduled' : null } |
  { 'inProgress' : null } |
  { 'postponed' : null };
export interface GameTotal {
  'homePace' : PaceProfile,
  'gameId' : GameId,
  'refereeProfile' : [] | [RefereeProfile],
  'impliedTotal' : [] | [number],
  'projectedTotal' : [] | [number],
  'recentTrends' : Array<ScoringTrend>,
  'confidenceReport' : [] | [TotalsConfidenceReport],
  'awayPace' : PaceProfile,
  'injuryImpact' : string,
}
export interface GamesResponse {
  'gamesDate' : string,
  'isUpcomingDate' : boolean,
  'games' : Array<Game>,
}
export interface InjuryReport {
  'status' : string,
  'playerId' : PlayerId,
  'team' : string,
  'description' : string,
  'updatedAt' : string,
  'playerName' : string,
}
export interface OddsLine {
  'homeMoneyline' : [] | [bigint],
  'overUnder' : [] | [number],
  'awaySpreadOdds' : [] | [bigint],
  'awayMoneyline' : [] | [bigint],
  'overOdds' : [] | [bigint],
  'awaySpread' : [] | [number],
  'homeSpreadOdds' : [] | [bigint],
  'homeSpread' : [] | [number],
  'bookmaker' : string,
  'underOdds' : [] | [bigint],
  'updatedAt' : string,
}
export interface PaceProfile {
  'defensiveEfficiency' : number,
  'pace' : number,
  'avgPointsAgainst' : number,
  'avgPointsFor' : number,
  'offensiveEfficiency' : number,
  'teamId' : TeamId,
  'last5Avg' : number,
}
export interface Player {
  'id' : PlayerId,
  'name' : string,
  'team' : string,
  'jerseyNumber' : string,
  'injuryStatus' : string,
  'position' : string,
}
export type PlayerId = string;
export interface PlayerProp {
  'seasonAvgPoints' : number,
  'player' : Player,
  'seasonUsageRate' : number,
  'matchupDefRating' : [] | [number],
  'seasonAvgMinutes' : number,
  'propLines' : Array<PropLine>,
  'confidenceReport' : [] | [ConfidenceReport],
  'backToBack' : boolean,
  'recentGames' : Array<PlayerRecentGame>,
  'homeAwaySplit' : number,
}
export interface PlayerPropsAnalysis {
  'gameId' : GameId,
  'players' : Array<PlayerProp>,
  'analysisGeneratedAt' : string,
}
export interface PlayerRecentGame {
  'fieldGoalAttempts' : number,
  'date' : string,
  'minutes' : number,
  'usageRate' : number,
  'points' : number,
  'opponent' : string,
}
export interface PropLine {
  'overOdds' : bigint,
  'line' : number,
  'bookmaker' : string,
  'underOdds' : bigint,
}
export interface RefereeProfile {
  'overRate' : [] | [number],
  'name' : string,
  'avgFoulsPerGame' : [] | [number],
  'avgFreeThrowsPerGame' : [] | [number],
  'tendency' : string,
}
export type Result = { 'ok' : boolean } |
  { 'err' : ApiError };
export type Result_1 = { 'ok' : string } |
  { 'err' : ApiError };
export type Result_2 = { 'ok' : GamesResponse } |
  { 'err' : ApiError };
export type Result_3 = { 'ok' : PlayerPropsAnalysis } |
  { 'err' : ApiError };
export type Result_4 = { 'ok' : Array<OddsLine> } |
  { 'err' : ApiError };
export type Result_5 = { 'ok' : GameTotal } |
  { 'err' : ApiError };
export type Result_6 = { 'ok' : GameInvestigation } |
  { 'err' : ApiError };
export interface ScoringTrend {
  'result' : string,
  'overUnder' : number,
  'teamTotal' : number,
  'date' : string,
  'gameTotal' : number,
  'opponent' : string,
}
export interface Team {
  'id' : TeamId,
  'city' : string,
  'name' : string,
  'abbreviation' : string,
  'record' : string,
}
export type TeamId = string;
export interface TeamStats {
  'pace' : [] | [number],
  'recentForm' : Array<bigint>,
  'homeAwayRecord' : string,
  'defensiveRating' : [] | [number],
  'teamId' : TeamId,
  'restDays' : bigint,
  'offensiveRating' : [] | [number],
  'pointsPerGame' : [] | [number],
}
export interface TotalsConfidenceReport {
  'overUnderEdge' : string,
  'keyFactors' : Array<string>,
  'reasoning' : string,
  'score' : bigint,
  'projectedTotal' : [] | [number],
  'grade' : string,
  'recommendation' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'getApiStatus' : ActorMethod<[], ApiStatus>,
  'getBetHistory' : ActorMethod<[], Array<BetRecommendation>>,
  'getBetHistoryStats' : ActorMethod<[], BetHistoryStats>,
  'getGameInvestigation' : ActorMethod<[GameId, string], Result_6>,
  'getGameTotalsAnalysis' : ActorMethod<[GameId, string, string], Result_5>,
  'getMultiBookOdds' : ActorMethod<[GameId], Result_4>,
  'getPlayerPropsAnalysis' : ActorMethod<[GameId], Result_3>,
  'getPropsAIAnalysis' : ActorMethod<[string, string], string>,
  'getTodaysGames' : ActorMethod<[], Result_2>,
  'getTotalsAIAnalysis' : ActorMethod<[string, string], string>,
  'isBdlApiConfigured' : ActorMethod<[], boolean>,
  'isOddsApiConfigured' : ActorMethod<[], boolean>,
  'isOpenAIConfigured' : ActorMethod<[], boolean>,
  'saveBetRecommendation' : ActorMethod<[BetRecommendation], Result_1>,
  'setBdlApiKey' : ActorMethod<[string], undefined>,
  'setOddsApiKey' : ActorMethod<[string], undefined>,
  'setOpenAIApiKey' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBetOutcome' : ActorMethod<[string, BetStatus, [] | [string]], Result>,
  'updateClosingLine' : ActorMethod<[string, string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
